#!/usr/bin/python

# mx send port -arg1 val1 -arg2 val2 ...

import os,sys,zmq,json

context = zmq.Context()
sock = context.socket(zmq.DEALER)
sock.connect(os.environ["MX_IPC_PATH"])
mx_cmd = sys.argv[1]
if(mx_cmd == "send"):
    argns = ["_mx_cmd","_name"]+[x[1:] for x in sys.argv[1:] if len(x) > 0 and x[0] == '-']
    argvs = [x for x in sys.argv[1:] if len(x) == 0 or x[0] != '-']
else:
    print("Bad command")
    sys.exit(1)

if(len(argns) != len(argvs)):
    print("Argument mismatch")
    sys.exit(2)

args = {argns[i]:argvs[i] for i in range(min(len(argns),len(argvs)))}
sock.send_unicode(json.dumps(args))
