#!/bin/bash
#export MC_ADDR='tcp://localhost:'"$1"
export PYTHONPATH="$(realpath $( dirname "${BASH_SOURCE[0]}" )'/../../libmango/py' )"
echo $PYTHONPATH
echo "MID" $MANGO_ID
#export MANGO_ID=$2
python mx_agent.py &
export MX_PID=$!
echo $MX_PID
while [[ ! -f .run/$MX_PID && ! -p .run/"$MX_PID"_out ]]; do
  [[ -f .run/"$MX_PID"_out ]] && echo hello;
  [[ ! -f .run/"$MX_PID"_out ]] && echo hello2;
  printf '.';
  sleep 1;
  done
bash --init-file .run/$MX_PID
#screen -c screenrc

