#!/bin/bash
export PYTHONPATH="$(realpath $( dirname "${BASH_SOURCE[0]}" )'/../../libmango/py' )"
echo $PYTHONPATH
echo "MID" $MANGO_ID
python mx_agent.py &
export MX_PID=$!
echo $MX_PID
while [[ ! -f .run/"$MX_PID"_init.tmp && ! -p .run/"$MX_PID"_out.tmp ]]; do
  [[ -f .run/"$MX_PID"_out.tmp ]] && echo hello;
  [[ ! -f .run/"$MX_PID"_out.tmp ]] && echo hello2;
  printf '.';
  sleep 1;
  done
screen -S "$MANGO_ID" -c screenrc
