// Code generated by goyacc -o src/mc/routeparser/routeparser.go -v y src/mc/routeparser/routeparser.go.y. DO NOT EDIT.

//line src/mc/routeparser/routeparser.go.y:2
package routeparser

import __yyfmt__ "fmt"

//line src/mc/routeparser/routeparser.go.y:2
import (
	"fmt"
	"strconv"
)

type Token struct {
	token    int
	literal  string
	position Position
}
type Node struct {
	Name string
}
type Route struct {
	Source     string
	Transforms []*Transform
	Dest       string
}
type RouteList struct {
	Routes []*Route
}
type Transform struct {
	Type      string
	Condition *Expression
	Script    *Script
	Source    string
}
type Expression struct {
	Operation string
	Args      []*Expression
	Value     *Value
}
type Script struct {
	Statements []*Statement
}
type Statement struct {
	Operation string
	Args      []*Value
}
type Value struct {
	Type      string
	NameVal   string
	IntVal    int
	FloatVal  float64
	StringVal string
	ExprVal   *Expression
}

// type Transform struct {
// 	Type FILTER|EDIT|REPLACE|FILTEREDIT|FILTERREPLACE
// }
// type Operation struct {
// 	Op string
// 	Args []Operation
// 	Kwargs map[string]Operation
// 	Execute Script
// }
// type Script struct {
// 	Ops []Op
// }

//line src/mc/routeparser/routeparser.go.y:63
type yySymType struct {
	yys        int
	token      Token
	routes     []*Route
	transforms []*Transform
	transform  *Transform
	expression *Expression
	script     []*Statement
	statement  *Statement
	node       *Node
}

const IDENT = 57346
const VAR = 57347
const NAME = 57348
const NUMBER = 57349
const STRING = 57350
const NOT = 57351
const AND = 57352
const OR = 57353
const IS = 57354
const EQ = 57355
const UNARY = 57356
const GE = 57357
const LE = 57358

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"VAR",
	"NAME",
	"NUMBER",
	"STRING",
	"NOT",
	"AND",
	"OR",
	"IS",
	"EQ",
	"'?'",
	"'%'",
	"'='",
	"'{'",
	"'}'",
	"'<'",
	"'>'",
	"':'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"UNARY",
	"GE",
	"LE",
	"';'",
	"'('",
	"')'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line src/mc/routeparser/routeparser.go.y:256

type RouteLexer struct {
	s      *RouteScanner
	Nodes  map[string]string
	result RouteList
}

func (l *RouteLexer) Lex(lval *yySymType) int {
	tok, lit, pos := l.s.Scan()
	if tok == EOF {
		return 0
	}
	lval.token = Token{token: tok, literal: lit, position: pos}
	fmt.Println("Lexed", tok, lit, pos)
	return tok
}
func (l *RouteLexer) Error(e string) {
	fmt.Println("ERROR", e)
}
func (r *Route) ToString() string {
	return fmt.Sprintf("%s > %s", r.Source, r.Dest)
}
func Parse(exp string, nodes map[string]string) RouteList {
	l := new(RouteLexer)
	l.Nodes = nodes
	l.s = new(RouteScanner)
	l.s.Init(exp)
	//l.Init(strings.NewReader(exp))
	yyParse(l)
	return l.result
}

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 159

var yyAct = [...]int{

	27, 25, 36, 21, 35, 47, 20, 22, 40, 39,
	3, 31, 32, 33, 34, 19, 37, 38, 13, 43,
	58, 16, 23, 46, 41, 42, 12, 15, 44, 24,
	5, 4, 48, 49, 50, 51, 52, 53, 54, 55,
	56, 57, 14, 36, 29, 35, 3, 59, 60, 40,
	39, 26, 31, 32, 33, 34, 7, 37, 38, 61,
	36, 1, 35, 0, 0, 0, 40, 39, 0, 31,
	32, 33, 34, 0, 37, 38, 45, 36, 0, 35,
	0, 0, 62, 40, 39, 0, 31, 32, 33, 34,
	0, 37, 38, 36, 0, 35, 0, 0, 30, 40,
	39, 0, 31, 32, 33, 34, 0, 37, 38, 36,
	28, 35, 0, 20, 22, 40, 39, 0, 31, 32,
	33, 34, 0, 37, 38, 0, 0, 0, 36, 23,
	35, 3, 0, 0, 40, 39, 24, 31, 32, 33,
	34, 8, 9, 10, 2, 0, 0, 0, 0, 6,
	11, 0, 0, 0, 0, 0, 0, 17, 18,
}
var yyPact = [...]int{

	42, -1000, 11, -1000, 127, 6, -1000, -2, 25, 10,
	4, -1000, 42, 42, -1, 106, 40, -1000, -1000, 80,
	-1000, -1000, -1000, -1, -1, 1, 106, 47, 7, -16,
	-1000, -1, -1, -1, -1, -1, -1, -1, -1, -1,
	-1, 96, -11, -1000, -1000, -1000, -1, -1, 96, 96,
	96, 96, 96, 96, 115, 115, 96, 96, -1000, 30,
	64, -1000, -1000,
}
var yyPgo = [...]int{

	0, 61, 144, 56, 1, 51, 0,
}
var yyR1 = [...]int{

	0, 1, 1, 1, 1, 2, 3, 3, 3, 4,
	4, 5, 5, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6,
}
var yyR2 = [...]int{

	0, 3, 3, 4, 5, 1, 4, 4, 6, 1,
	2, 2, 4, 1, 1, 1, 2, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3,
}
var yyChk = [...]int{

	-1000, -1, -2, 4, 20, 19, -2, -3, 14, 15,
	16, -2, 20, 20, 17, 17, 17, -2, -2, -6,
	7, 4, 8, 23, 30, -4, -5, -6, 4, 4,
	18, 22, 23, 24, 25, 15, 13, 27, 28, 20,
	19, -6, -6, 18, -4, 29, 16, 21, -6, -6,
	-6, -6, -6, -6, -6, -6, -6, -6, 31, -6,
	-6, 29, 18,
}
var yyDef = [...]int{

	0, -2, 0, 5, 0, 0, 1, 0, 0, 0,
	0, 2, 0, 0, 0, 0, 0, 3, 4, 0,
	13, 14, 15, 0, 0, 0, 9, 0, 14, 0,
	6, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 16, 0, 7, 10, 11, 0, 0, 18, 19,
	20, 21, 22, 23, 24, 25, 26, 27, 17, 0,
	0, 12, 8,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 15, 3, 3,
	30, 31, 24, 22, 3, 23, 3, 25, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 21, 29,
	19, 16, 20, 14, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 17, 3, 18,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 26, 27, 28,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:89
		{
			fmt.Println("C")
			yyVAL.routes = nil
			if l, ok := yylex.(*RouteLexer); ok {
				l.result = RouteList{Routes: []*Route{&Route{Source: yyDollar[1].node.Name, Dest: yyDollar[3].node.Name}}}
			}
		}
	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:97
		{
			fmt.Println("B")
			yyVAL.routes = nil
			if l, ok := yylex.(*RouteLexer); ok {
				l.result = RouteList{Routes: []*Route{&Route{Source: yyDollar[3].node.Name, Dest: yyDollar[1].node.Name}}}
			}
		}
	case 3:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:105
		{
			yyVAL.routes = nil
			if l, ok := yylex.(*RouteLexer); ok {
				l.result = RouteList{Routes: []*Route{
					&Route{Source: yyDollar[1].node.Name, Dest: yyDollar[4].node.Name},
					&Route{Source: yyDollar[4].node.Name, Dest: yyDollar[1].node.Name}}}
			}
		}
	case 4:
		yyDollar = yyS[yypt-5 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:114
		{
			yyVAL.routes = nil
			fmt.Println("A")
			if l, ok := yylex.(*RouteLexer); ok {
				l.result = RouteList{Routes: []*Route{&Route{Source: yyDollar[1].node.Name, Dest: yyDollar[5].node.Name, Transforms: []*Transform{yyDollar[3].transform}}}}
			}
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:123
		{
			fmt.Println("NODE", yyDollar[1].token.literal)
			yyVAL.node = &Node{Name: yyDollar[1].token.literal}
		}
	case 6:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:129
		{
			yyVAL.transform = &Transform{Source: yyDollar[1].token.literal}
		}
	case 7:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:133
		{
			yyVAL.transform = &Transform{Source: yyDollar[1].token.literal}
		}
	case 8:
		yyDollar = yyS[yypt-6 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:137
		{
			yyVAL.transform = &Transform{Source: yyDollar[1].token.literal}
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:143
		{
			yyVAL.script = []*Statement{yyDollar[1].statement}
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:147
		{
			yyVAL.script = append([]*Statement{yyDollar[1].statement}, yyDollar[2].script...)
		}
	case 11:
		yyDollar = yyS[yypt-2 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:152
		{
			yyVAL.statement = &Statement{
				Operation: "expr",
				Args: []*Value{
					&Value{Type: "expr", ExprVal: yyDollar[1].expression}}}
		}
	case 12:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:159
		{
			yyVAL.statement = &Statement{
				Operation: "assign",
				Args: []*Value{
					&Value{Type: "var", NameVal: yyDollar[1].token.literal},
					&Value{Type: "expr", ExprVal: yyDollar[3].expression}}}
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:167
		{
			x, _ := strconv.Atoi(yyDollar[1].token.literal)
			yyVAL.expression = &Expression{
				Operation: "val",
				Value:     &Value{Type: "int", IntVal: x}}
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:174
		{
			yyVAL.expression = &Expression{
				Operation: "val",
				Value:     &Value{Type: "var", NameVal: yyDollar[1].token.literal}}
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:180
		{
			yyVAL.expression = &Expression{
				Operation: "string",
				Value:     &Value{Type: "var", StringVal: yyDollar[1].token.literal}}
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:186
		{
			yyVAL.expression = &Expression{
				Operation: "-",
				Args:      []*Expression{yyDollar[2].expression}}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:192
		{
			yyVAL.expression = yyDollar[2].expression
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:196
		{
			yyVAL.expression = &Expression{
				Operation: "+",
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:202
		{
			yyVAL.expression = &Expression{
				Operation: "-",
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:208
		{
			yyVAL.expression = &Expression{
				Operation: "*",
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:214
		{
			yyVAL.expression = &Expression{
				Operation: "/",
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:220
		{
			yyVAL.expression = &Expression{
				Operation: "%",
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:226
		{
			yyVAL.expression = &Expression{
				Operation: "==",
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:232
		{
			yyVAL.expression = &Expression{
				Operation: ">=",
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:238
		{
			yyVAL.expression = &Expression{
				Operation: "<=",
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:244
		{
			yyVAL.expression = &Expression{
				Operation: ">",
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/routeparser/routeparser.go.y:250
		{
			yyVAL.expression = &Expression{
				Operation: "<",
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	}
	goto yystack /* stack new state and value */
}
