// Code generated by goyacc -o src/mc/router/parser.go -v y src/mc/router/parser.go.y. DO NOT EDIT.

//line src/mc/router/parser.go.y:2
package router

import __yyfmt__ "fmt"

//line src/mc/router/parser.go.y:2
import (
	"strconv"
	//"fmt"
)

type Token struct {
	token    int
	literal  string
	position Position
}
type Script struct {
	Statements []*Statement
}
type Statement struct {
	Name string
	Val  *Expression
}

//line src/mc/router/parser.go.y:20
type yySymType struct {
	yys        int
	token      Token
	routes     []*Route
	transforms *Route
	transform  *Transform
	expression *Expression
	script     []*Expression
	node       *Node
}

const IDENT = 57346
const VAR = 57347
const NAME = 57348
const NUMBER = 57349
const STRING = 57350
const AND = 57351
const OR = 57352
const EQ = 57353
const LE = 57354
const GE = 57355
const PE = 57356
const ME = 57357
const TE = 57358
const DE = 57359
const RE = 57360
const XE = 57361
const SUB = 57362
const UNARY = 57363
const IS = 57364
const NOT = 57365

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"VAR",
	"NAME",
	"NUMBER",
	"STRING",
	"AND",
	"OR",
	"EQ",
	"LE",
	"GE",
	"PE",
	"ME",
	"TE",
	"DE",
	"RE",
	"XE",
	"SUB",
	"'?'",
	"'%'",
	"'='",
	"'{'",
	"'}'",
	"'['",
	"']'",
	"'<'",
	"'>'",
	"':'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'&'",
	"'|'",
	"'^'",
	"UNARY",
	"IS",
	"NOT",
	"';'",
	"'('",
	"')'",
	"','",
	"'.'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line src/mc/router/parser.go.y:350

func Parse(exp string) []*Route {
	l := new(RouteLexer)
	l.s = new(RouteScanner)
	l.s.Init(exp)
	//l.Init(strings.NewReader(exp))
	yyParse(l)
	return l.result
}

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 438

var yyAct = [...]int{

	48, 51, 50, 93, 52, 29, 78, 64, 5, 4,
	14, 3, 79, 77, 55, 17, 30, 21, 32, 16,
	15, 49, 33, 59, 60, 61, 62, 63, 75, 53,
	54, 25, 58, 32, 22, 26, 13, 33, 65, 66,
	67, 68, 69, 70, 71, 72, 73, 74, 56, 76,
	34, 23, 3, 24, 31, 81, 41, 43, 42, 27,
	83, 84, 85, 86, 87, 88, 89, 40, 8, 28,
	7, 47, 1, 45, 44, 3, 36, 37, 38, 39,
	91, 0, 0, 92, 0, 20, 41, 43, 42, 101,
	46, 0, 9, 10, 11, 0, 0, 40, 0, 0,
	100, 47, 102, 45, 44, 0, 36, 37, 38, 39,
	41, 43, 42, 0, 0, 0, 0, 0, 0, 0,
	46, 40, 0, 0, 0, 47, 0, 45, 44, 0,
	36, 37, 38, 39, 41, 43, 42, 0, 0, 0,
	99, 0, 0, 0, 46, 40, 0, 0, 0, 47,
	0, 45, 44, 0, 36, 37, 38, 39, 41, 43,
	42, 0, 0, 0, 98, 0, 0, 0, 46, 40,
	0, 0, 0, 47, 0, 45, 44, 0, 36, 37,
	38, 39, 41, 43, 42, 0, 0, 0, 97, 0,
	0, 0, 46, 40, 0, 0, 0, 47, 0, 45,
	44, 0, 36, 37, 38, 39, 41, 43, 42, 0,
	0, 0, 96, 0, 0, 0, 46, 40, 0, 0,
	0, 47, 0, 45, 44, 0, 36, 37, 38, 39,
	41, 43, 42, 0, 0, 0, 95, 0, 0, 0,
	46, 40, 0, 0, 0, 47, 0, 45, 44, 0,
	36, 37, 38, 39, 41, 43, 42, 0, 0, 0,
	94, 0, 0, 0, 46, 40, 0, 0, 0, 47,
	90, 45, 44, 0, 36, 37, 38, 39, 41, 43,
	42, 0, 0, 0, 0, 0, 0, 0, 46, 40,
	0, 0, 0, 47, 0, 45, 44, 0, 36, 37,
	38, 39, 41, 43, 42, 0, 0, 0, 0, 0,
	82, 0, 46, 40, 0, 0, 0, 47, 0, 45,
	44, 0, 36, 37, 38, 39, 41, 43, 42, 0,
	0, 0, 0, 0, 0, 80, 46, 40, 0, 0,
	0, 47, 0, 45, 44, 0, 36, 37, 38, 39,
	41, 43, 42, 0, 0, 0, 57, 0, 0, 0,
	46, 40, 0, 0, 35, 47, 0, 45, 44, 0,
	36, 37, 38, 39, 41, 43, 42, 0, 0, 0,
	0, 0, 0, 0, 46, 40, 0, 0, 0, 47,
	0, 45, 44, 0, 36, 37, 38, 39, 41, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 46, 40,
	0, 0, 0, 47, 0, 45, 44, 0, 36, 37,
	38, 39, 2, 0, 0, 0, 0, 6, 12, 0,
	0, 0, 46, 0, 0, 0, 18, 19,
}
var yyPact = [...]int{

	48, -1000, -20, -1000, 71, 7, -1000, -1000, -19, -4,
	-5, -9, -1000, 48, 71, 27, 27, 46, -1000, -1000,
	-1000, 339, -1000, 17, 27, -38, -1000, 27, 27, -1000,
	-11, 27, 315, 9, -23, -1000, 27, 27, 27, 27,
	27, 27, 27, 27, 27, 27, 24, 27, -12, -24,
	-15, 291, 27, 363, 267, -1000, -1000, -1000, 27, 27,
	27, 27, 27, 27, 27, 363, 363, 363, 363, 363,
	363, 387, 387, 363, 363, -1000, 243, -1000, 27, -1000,
	27, -40, -1000, 219, 195, 171, 147, 123, 99, 75,
	-1000, 45, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 17, -1000,
}
var yyPgo = [...]int{

	0, 72, 422, 70, 68, 16, 5, 54, 1, 0,
	2,
}
var yyR1 = [...]int{

	0, 1, 1, 1, 1, 2, 3, 3, 4, 4,
	4, 5, 5, 7, 7, 7, 7, 7, 7, 7,
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
	8, 8, 8, 8, 8, 8, 8, 8, 9, 9,
	10, 10, 6, 6, 6,
}
var yyR2 = [...]int{

	0, 3, 3, 4, 3, 1, 3, 3, 4, 4,
	6, 1, 2, 2, 4, 4, 4, 4, 4, 4,
	1, 3, 3, 4, 1, 2, 3, 1, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 5,
	1, 3, 3, 4, 1,
}
var yyChk = [...]int{

	-1000, -1, -2, 4, 29, 28, -2, -3, -4, 21,
	22, 23, -2, 29, 29, 24, 24, 24, -2, -2,
	-3, -8, 7, 24, 26, 4, 8, 32, 42, -6,
	-5, -7, -8, -6, 4, 25, 31, 32, 33, 34,
	22, 11, 13, 12, 29, 28, 45, 26, -9, 4,
	-10, -8, 42, -8, -8, 25, -5, 41, 23, 14,
	15, 16, 17, 18, 30, -8, -8, -8, -8, -8,
	-8, -8, -8, -8, -8, 4, -8, 25, 30, 27,
	44, -10, 43, -8, -8, -8, -8, -8, -8, -8,
	27, -8, -10, 43, 41, 41, 41, 41, 41, 41,
	25, 44, -9,
}
var yyDef = [...]int{

	0, -2, 0, 5, 0, 0, 1, 4, 0, 0,
	0, 0, 2, 0, 0, 0, 0, 0, 3, 6,
	7, 0, 20, 0, 0, 44, 24, 0, 0, 27,
	0, 11, 0, 27, 0, 8, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 40, 0, 25, 0, 9, 12, 13, 0, 0,
	0, 0, 0, 0, 0, 28, 29, 30, 31, 32,
	33, 34, 35, 36, 37, 42, 0, 21, 0, 22,
	0, 0, 26, 0, 0, 0, 0, 0, 0, 0,
	43, 38, 41, 23, 14, 15, 16, 17, 18, 19,
	10, 0, 39,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 22, 35, 3,
	42, 43, 33, 31, 44, 32, 45, 34, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 30, 41,
	28, 23, 29, 21, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 26, 3, 27, 37, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 24, 36, 25,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 38,
	39, 40,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:49
		{
			// fmt.Println("C")
			yyVAL.routes = nil
			if l, ok := yylex.(*RouteLexer); ok {
				l.result = []*Route{&Route{Source: yyDollar[1].node.Name, Dest: yyDollar[3].node.Name}}
			}
		}
	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:57
		{
			// fmt.Println("B")
			yyVAL.routes = nil
			if l, ok := yylex.(*RouteLexer); ok {
				l.result = []*Route{&Route{Source: yyDollar[3].node.Name, Dest: yyDollar[1].node.Name}}
			}
		}
	case 3:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/mc/router/parser.go.y:65
		{
			yyVAL.routes = nil
			if l, ok := yylex.(*RouteLexer); ok {
				l.result = []*Route{
					&Route{Source: yyDollar[1].node.Name, Dest: yyDollar[4].node.Name},
					&Route{Source: yyDollar[4].node.Name, Dest: yyDollar[1].node.Name}}
			}
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:74
		{
			yyVAL.routes = nil
			// fmt.Println("A")
			if l, ok := yylex.(*RouteLexer); ok {
				l.result = []*Route{
					&Route{
						Source:     yyDollar[1].node.Name,
						Dest:       yyDollar[3].transforms.Dest,
						Transforms: yyDollar[3].transforms.Transforms}}
			}
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/mc/router/parser.go.y:87
		{
			// fmt.Println("NODE",$1.literal)
			yyVAL.node = &Node{Name: yyDollar[1].token.literal}
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:93
		{
			yyVAL.transforms = &Route{
				Dest:       yyDollar[3].node.Name,
				Transforms: []*Transform{yyDollar[1].transform}}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:99
		{
			yyVAL.transforms = &Route{
				Dest:       yyDollar[3].transforms.Dest,
				Transforms: append([]*Transform{yyDollar[1].transform}, yyDollar[3].transforms.Transforms...)}
		}
	case 8:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/mc/router/parser.go.y:106
		{
			yyVAL.transform = &Transform{
				Type:   "filter",
				Source: yyDollar[3].expression.ToString()}
		}
	case 9:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/mc/router/parser.go.y:112
		{
			yyVAL.transform = &Transform{
				Type: "map"}
		}
	case 10:
		yyDollar = yyS[yypt-6 : yypt+1]
//line src/mc/router/parser.go.y:117
		{
			yyVAL.transform = &Transform{
				Type:   "replace",
				Source: yyDollar[5].expression.ToString()}
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/mc/router/parser.go.y:125
		{
			yyVAL.script = []*Expression{yyDollar[1].expression}
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line src/mc/router/parser.go.y:129
		{
			yyVAL.script = append([]*Expression{yyDollar[1].expression}, yyDollar[2].script...)
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line src/mc/router/parser.go.y:134
		{
			yyVAL.expression = yyDollar[1].expression
		}
	case 14:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/mc/router/parser.go.y:138
		{
			yyVAL.expression = &Expression{
				Operation: OP_ASSIGN,
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 15:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/mc/router/parser.go.y:144
		{
			yyVAL.expression = &Expression{
				Operation: OP_ASSIGN,
				Args: []*Expression{
					yyDollar[1].expression,
					&Expression{
						Operation: OP_PLUS,
						Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}}}
		}
	case 16:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/mc/router/parser.go.y:154
		{
			yyVAL.expression = &Expression{
				Operation: OP_ASSIGN,
				Args: []*Expression{
					yyDollar[1].expression,
					&Expression{
						Operation: OP_MINUS,
						Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}}}
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/mc/router/parser.go.y:164
		{
			yyVAL.expression = &Expression{
				Operation: OP_ASSIGN,
				Args: []*Expression{
					yyDollar[1].expression,
					&Expression{
						Operation: OP_MUL,
						Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}}}
		}
	case 18:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/mc/router/parser.go.y:174
		{
			yyVAL.expression = &Expression{
				Operation: OP_ASSIGN,
				Args: []*Expression{
					yyDollar[1].expression,
					&Expression{
						Operation: OP_DIV,
						Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}}}
		}
	case 19:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/mc/router/parser.go.y:184
		{
			yyVAL.expression = &Expression{
				Operation: OP_ASSIGN,
				Args: []*Expression{
					yyDollar[1].expression,
					&Expression{
						Operation: OP_MOD,
						Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}}}
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/mc/router/parser.go.y:194
		{
			x, _ := strconv.Atoi(yyDollar[1].token.literal)
			yyVAL.expression = &Expression{
				Operation: OP_NUM,
				Value:     &Value{Type: VAL_NUM, NumVal: float64(x)}}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:201
		{
			yyVAL.expression = yyDollar[2].expression
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:205
		{
			yyVAL.expression = yyDollar[2].expression
		}
	case 23:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/mc/router/parser.go.y:209
		{
			yyVAL.expression = &Expression{
				Operation: OP_CALL,
				Args: []*Expression{
					MakeNameExpression(yyDollar[1].token.literal),
					yyDollar[3].expression}}
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/mc/router/parser.go.y:217
		{
			yyVAL.expression = &Expression{
				Operation: OP_STRING,
				Value:     &Value{Type: VAL_STRING, StringVal: yyDollar[1].token.literal}}
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line src/mc/router/parser.go.y:223
		{
			yyVAL.expression = &Expression{
				Operation: OP_UMINUS,
				Args:      []*Expression{yyDollar[2].expression}}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:229
		{
			yyVAL.expression = yyDollar[2].expression
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/mc/router/parser.go.y:233
		{
			yyVAL.expression = yyDollar[1].expression
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:237
		{
			yyVAL.expression = &Expression{
				Operation: OP_PLUS,
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:243
		{
			yyVAL.expression = &Expression{
				Operation: OP_MINUS,
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:249
		{
			yyVAL.expression = &Expression{
				Operation: OP_MUL,
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:255
		{
			yyVAL.expression = &Expression{
				Operation: OP_DIV,
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:261
		{
			yyVAL.expression = &Expression{
				Operation: OP_MOD,
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:267
		{
			yyVAL.expression = &Expression{
				Operation: OP_EQ,
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:273
		{
			yyVAL.expression = &Expression{
				Operation: OP_GE,
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:279
		{
			yyVAL.expression = &Expression{
				Operation: OP_LE,
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:285
		{
			yyVAL.expression = &Expression{
				Operation: OP_GT,
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:291
		{
			yyVAL.expression = &Expression{
				Operation: OP_LT,
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:298
		{
			yyVAL.expression = &Expression{
				Operation: OP_MAP,
				Args: []*Expression{
					MakeNameExpression(yyDollar[1].token.literal),
					yyDollar[3].expression}}
		}
	case 39:
		yyDollar = yyS[yypt-5 : yypt+1]
//line src/mc/router/parser.go.y:306
		{
			args := []*Expression{
				MakeNameExpression(yyDollar[1].token.literal),
				yyDollar[3].expression}
			yyVAL.expression = &Expression{
				Operation: OP_MAP,
				Args:      append(args, yyDollar[5].expression.Args...)}
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/mc/router/parser.go.y:316
		{
			yyVAL.expression = &Expression{
				Operation: OP_LIST,
				Args:      []*Expression{yyDollar[1].expression}}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:322
		{
			args := []*Expression{yyDollar[1].expression}
			yyVAL.expression = &Expression{
				Operation: OP_LIST,
				Args:      append(args, yyDollar[3].expression.Args...)}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line src/mc/router/parser.go.y:330
		{
			yyVAL.expression = &Expression{
				Operation: OP_MAPVAR,
				Args: []*Expression{
					yyDollar[1].expression,
					MakeNameExpression(yyDollar[3].token.literal)}}
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line src/mc/router/parser.go.y:338
		{
			yyVAL.expression = &Expression{
				Operation: OP_LISTVAR,
				Args:      []*Expression{yyDollar[1].expression, yyDollar[3].expression}}
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line src/mc/router/parser.go.y:344
		{
			yyVAL.expression = &Expression{
				Operation: OP_VAR,
				Value:     &Value{Type: VAL_NAME, NameVal: yyDollar[1].token.literal}}
		}
	}
	goto yystack /* stack new state and value */
}
